baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Shawn McDaniel'
theme = 'PaperMod'
pagination.pagerSize = 5 # Optional: Set number of posts per page

# Required for the search function to work
[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  description = "Welcome to my workspace"
  author = "Shawn McDaniel" # Add your name for metadata
  layoutReverse = true
  # defaultTheme = "auto" # Set default theme (auto, light, or dark)
  # disableThemeToggle = false # Allow users to switch themes

  # Show metadata on blog post list pages
  ShowReadingTime = true
  ShowWordCount = true

  # Add a button to copy code blocks
  showCodeCopyButtons = true



  # Profile mode for the home page
  [params.profileMode]
    enabled = true
    title = "Shawn McDaniel"
    subtitle = "Builder | Security Professional | Technology Enjoyer"
    imageUrl = "/avatar.png" # Path relative to assets folder
    imageWidth = 420
    imageHeight = 420

    [[params.profileMode.buttons]]
      name = "Blog"
      url = "/posts" # or "/blog"

    [[params.profileMode.buttons]]
      name = "Projects"
      url = "/projects"

  # Social Icons
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/dmgedgoods/"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/smackdaniel/"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:shawn@apt-i.com"

# Main menu, which appears in the header
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/" # or wherever your blog posts are
    weight = 20
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 30
